name = "HTML"
extensions = [".htm", ".html"]

folding = [
	["<head", "</head>"],
	["<body", "</body>"],
	["<table", "</table>"], 
	["<form", "</form>"],
	["<div", "</div>"],
	["<script", "</script>"],
	["<tr", "</tr>"]
]

styles = [
	["(<!--.*?-->)|(<!--.*)", "comment"],
	["(<!--.*?-->)|(.*-->)", "comment"],
	["<|/>|</|>", "keyword"],
	["<(?<range>[!\w:]+)", "keyword"],
	["</(?<range>[\w:]+)>", "keyword"],
	["[\\w\\d\\-]{1,20}?=(?<range>'[^']*')|[\\w\\d\-]{1,20}=(?<range>\"[^\"]*\")|[\\w\\d\\-]{1,20}=(?<range>[\\w\\d\\-]{1,20})", "string"]
]
